apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-app
  namespace: release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3-app
  template:
    metadata:
      labels:
        app: task3-app
    spec:
      containers:
        - name: task3-app
          image: task3-app:1.0.0
          ports:
            - containerPort: 5000
