apiVersion: v1
kind: Service
metadata:
  name: task3-service
  namespace: dev
spec:
  selector:
    app: task3-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 5000
  type: ClusterIP
