- hosts: all
  become: true

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Install Helm archive
      get_url:
        url: https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Unarchive Helm
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Helm binary
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'
        remote_src: yes

    - name: Start Minikube
      shell: minikube start --driver=docker --force

    - name: Enable ingress
      shell: minikube addons enable ingress

    - name: Enable dashboard
      shell: minikube addons enable dashboard

    - name: Check kubectl version
      command: kubectl version --client
      register: kubectl_check
      changed_when: false

    - name: Check Minikube status
      command: minikube status
      register: minikube_check
      changed_when: false

    - name: Check Helm version
      command: helm version
      register: helm_check
      changed_when: false

    - name: Show kubectl version
      debug:
        var: kubectl_check.stdout_lines

    - name: Show Minikube status
      debug:
        var: minikube_check.stdout_lines

    - name: Show Helm version
      debug:
        var: helm_check.stdout_lines

    - name: Kill old kubectl proxy
      shell: pkill -f "kubectl proxy" || true

    - name: Start kubectl proxy (background)
      shell: |
        nohup kubectl proxy --address='0.0.0.0' --disable-filter=true --port=8001 
>/tmp/kubectl-proxy.log 2>&1 &
