name: Task3 Deploy

on:
  push:
    branches:
      - develop
    tags:
      - '1.0.0'

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy repo to server and deploy dev
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 159.89.12.21
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /root
            if [ ! -d exam-devops ]; then
              git clone https://github.com/ZorianaSh/exam-devops.git
            fi
            cd /root/exam-devops
            git fetch --all
            git checkout develop
            git pull origin develop

            eval $(minikube -p minikube docker-env)
            cd /root/exam-devops/task3/app
            docker build -t task3-app:develop .

            cd /root/exam-devops
            kubectl apply -f task3/k8s/dev/namespace.yaml
            kubectl apply -f task3/k8s/dev/deployment.yaml --dry-run=client
            kubectl apply -f task3/k8s/dev/service.yaml --dry-run=client
            kubectl apply -f task3/k8s/dev/

  deploy-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy repo to server and deploy release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 159.89.12.21
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /root
            if [ ! -d exam-devops ]; then
              git clone https://github.com/ZorianaSh/exam-devops.git
            fi
            cd /root/exam-devops
            git fetch --all
            git checkout main
            git pull origin main

            eval $(minikube -p minikube docker-env)
            cd /root/exam-devops/task3/app
            docker build -t task3-app:1.0.0 .

            cd /root/exam-devops
            kubectl apply -f task3/k8s/release/namespace.yaml
            kubectl apply -f task3/k8s/release/deployment.yaml --dry-run=client
            kubectl apply -f task3/k8s/release/service.yaml --dry-run=client
            kubectl apply -f task3/k8s/release/
