name: Task2 Ansible Setup

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 159.89.12.21 >> ~/.ssh/known_hosts

      - name: Create inventory
        run: |
          echo "[minikube]" > task2/inventory.ini
          echo "node1 ansible_host=159.89.12.21 ansible_user=root" >> task2/inventory.ini

      - name: Test connection
        run: ansible all -i task2/inventory.ini -m ping --private-key ~/.ssh/id_ed25519

      - name: Run playbook
        run: ansible-playbook -i task2/inventory.ini task2/playbook.yml --private-key ~/.ssh/id_ed25519
