name: Task2 Ansible Setup

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: "VM public IP"
        required: true
        default: "159.89.12.21"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ github.event.inputs.vm_ip }} >> ~/.ssh/known_hosts

      - name: Create inventory
        run: |
          echo "[minikube]" > task2/inventory.ini
          echo "node1 ansible_host=${{ github.event.inputs.vm_ip }} ansible_user=root" >> 
task2/inventory.ini

      - name: Test connection
        run: ansible all -i task2/inventory.ini -m ping --private-key ~/.ssh/id_ed25519

      - name: Run playbook
        run: ansible-playbook -i task2/inventory.ini task2/playbook.yml --private-key 
~/.ssh/id_ed25519
